spring:
  application:
    name: catalogue-service
  data:
    mongodb:
      uri: ${DATASOURCE_URI}
      database: ${DATASOURCE_DATABASE}
server:
  port: 8081
  servlet:
    context-path: '/catalogue'